version: '2'
services:
    splitit-app:
        image: splitit
        external_links:
            - splitit-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/SplitIt
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    splitit-postgresql:
        extends:
            file: postgresql.yml
            service: splitit-postgresql
